travis:
  secure:
    BINSTAR_TOKEN: hwg2+Rw9wFYj/iWtjRkCKrnWWwX+KJfK52jMBwpxpGc4IRFbeJ2niGK682b0EcFv6pU/cUCN89tOzxpuO28mw6B939v+nYBayeozTMeOXIBMRXd0dOJHna71iunmOUDFnOoYMQvShNqTUtV2DvsnDT38BmpCHfEUSigITP3rN4qqE0WAfBqJ55tbn9lxuIRzy17vUTdPXgmsBAPoRJaX2XBRDHLs/BNltxJw43DfgsSL1AheX2/lmtvqE62OpG/TnyQpLPgQxpZmeoNle+1pp6bNw9e2ToYaJYyGbd/7oHA0M6IWiZAkgw45hc+8UvP2cM1Gtyca4EAGIubPvpUtkf+lpzwwoxZwZaBtn5kydiV+ab8q6GmjLy01m9cZqSmOqEkS94yh8cLMCXAjU2qX5TnFOZfwmc35OfVKOupODXASL9YpBxoaGVTISf1JT5ThmsAgTcC/5I6SLGkKQbQ+55CqbA4aaK/OIEgULFUkv6xt62oIHNJ6ljnn7agqbHSgTP6SHDk5jwuJUCAAMOthfGQpbN3zZEoJ5coB626sMVCG2ghVv3iUXPvLzsm4Plptsr5dxhyxrVL1Uw63RNv1qrT+1jzcmDLGDHtjlBL8CtFv2OtojOXJPI3YqWaRDtdrj1GpeQZEEW2QW4Pmq0/gNLyzysueKPF3K2AhyEAb8YU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
