travis:
  secure:
    BINSTAR_TOKEN: H6hIYsZmiMra3T1F7kOTVaA7+AtNyHW2ffP0cSP7yjRpAS+0crFz0CGtUrHY7Sh8RuWS5Ulbo19W8N8PhvoNVV5zwCT5dWIxros61I0F8CLOjh5KL5dbMZOxmH87OX/oSME1XTJoSn3uMUBJrPWtKTBVBYxbIaMNUbJYVum2rMgm88IwOf0r+wfYxqsZZK9h999vfptFJLA0PFytybKHw2H0o1QVujVQNOm+C2ylppkowVazy0Sq4/dHUd0asg85Z1uKXF0YHcHZD+beFmmX/m4guX3T5uVZ0Dm7rVq5Eh6zIj3AOwBEL8Hbu6zhvU9lB/Kw7iL+tKlxqwKtIcRVE47g3sG9um7CUaYWPfLEUr9n5iVGc7LEaG3aZSv5UHWga1fGubRTLIejcMKOPkYsdCVz5houum56WfgbLQlzzuHrl8djrJZmWtOJtR/Blco14ZqgVe13FGj8LqMH9vfEm3VlOHmWK3Bdn0oG2VAsby2AYeloH3iyU68vedT2Um6YGAphV5MNNvmbNJ0WlmVIiHCYsUDJKesw41uHBTMhxglr57iTUWbrBQ25H4DNlD7/o+jFsGQNGz3okf3NUrqCl8eFRAjC7KYZMcI3Hj8XTrwkIobxUpdZcJTdOUTtctI8U9EhoEP2jKRzaqS0Ec74wxYw2baWn0UQ0NZH2RDa6RU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
