travis:
  secure:
    BINSTAR_TOKEN: ihTUsCnwY+QT2WsTU0l9Ah7FKlMsc64Gc/eiZwUml8pH/9oBro+4CGkHG90i/ZpL/0T1OAYz3wlO7QbVJTqPc0a3r9uJUJCWBJEYlZoDuUU7XPVgSiVtNOtLntdgMK6autcMDhneCIITlU6zGxEpVlBb078YE2kQlXqsugRYagTiWHG474lOv93wa11W+t06CyNwyyqAd+ECwocleuhE9UtRTWLg9S/aFqJJrqhwo1D5Wz/uDDTKSltA85pPGQQxZYoyUtSliYCrgF/hQ6H9WPFn+beEI2o2DtIkrFq9rESbKBlCTquIBLRDnni7ijTtFiFnbCzedH+lGnindr9nJq73k+CLdYvGhDDL5Tg0tgaRCCmQg2iQl9VqW2lQxYlZ7frbElj2BVoN6PwrKhGawIoqjBXCCWPFM9sYLOPgmsWQlrKvTRRI8JaN3jvzNLEfhCdLdVtGXgLlsl92+XsTiixdR8J3gGfEc1Gjqcdo9E0h0m3PEK1PeHSnl999cnSkGKg+sjH0UeFfUzeNmFC6v3PYS588YTDa/HVKcBwS+D+qCJt8L4sYp/ZJe9jy+v/YV/vWrwVezqEkXXnzi5NdHkjQBZCS6hsZjQ/keY4knq+H1+W8ZyEzaeFET037EQerb0c8rkYbA7OKYwUPURGKa2rZJEtEUpMM6C/cC9yoUuI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
