travis:
  secure:
    BINSTAR_TOKEN: GXlAxpfPmbxAqCJBg0hGBIjoTWr/iQaubvkb401jSnzpgOQwlfw70OsiMyapjDP2E2O7FE/We3zxDzBiu0/zbbsjg+6Z8n7P1SaXKLysX+LXm/vYvtmAuWRAu6APajRf5az04RlU9d+EudtFDM70+BkfBqJlZWxKYwN8GHhCs+8dHQoHnW4opf5HCGiQ3WcjgAncJMv1pekXJh4uKouFo6E9RhYhgeT0idbycnbz+D6+4HZ5X583rQcnbJpIhV9lcYQOoEf7YV11Px2mZzqy8bwlQxgWpLJJAq57bORG1ex2LOdhO0+ASlPs0ChqnauH6v6eWcpKCmOd7+F39jkpGL5YJ1PYfIXcgBjrnozUYqSlqjI+CBA59mpsjUh9Lk8YEvmDbY0Q1OTURyRcdFz8c1tA5qcCgQ8Z96vObhM9SS26c49qZIbbqpWamJBU8WN59LBDFUry6VzFxq7xZ2Ua6SqZ+/xIu8qAjqhsh6fpRD6wwRL/K3Ka4kP+UNJUtARPfBYhbSLRtoEk5VDF9IjF0JFOnRjJKyvv+u5spB2547jV/BJn9abCZ3e34BUxhBzh1Z9hJupwKTmJv7JbYd87XbIOB0lgn7zah8wdDVjmTJUNOAJGceaQC4+1Am5iS7eNEwG6CBORLbY0iA6sTYFV8kzqFOQMsmqDA6ZEGDClGmU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
